name: check

on:
  push:
  pull_request:

jobs:
  powershell:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Parse PowerShell scripts
        shell: pwsh
        run: ./scripts/check.ps1

