name: check

on:
  push:
  pull_request:

jobs:
  powershell:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check scripts
        shell: pwsh
        run: ./scripts/check.ps1
      - name: Build native app
        shell: pwsh
        run: ./scripts/build-exe.ps1
